"""empty message

Revision ID: bd29c4b2c3a4
Revises:
Create Date: 2026-03-29 15:54:07.425513

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "bd29c4b2c3a4"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
